name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - run: dotnet restore ./EventDrivenDotNet.sln
      - run: dotnet build ./EventDrivenDotNet.sln --no-restore -c Release
      - run: dotnet test ./EventDrivenDotNet.sln --no-build -c Release --verbosity normal